### ISSUE TITLE
No Russian language

### ISSUE THREAD

**Issue by Ctalin** [neatodev/BmLauncher#21]
After installing an additional patch for the Russian language. It does not appear in the game, possibly due to the fact that the launcher does not have a similar language add-on.

**Comment by neatodev** [comment]
The launcher only supports official languages (so far). Please provide details about installing and using community made language patches so I can look into it.

**Comment by w4rd3ll** [comment]
Hi, I found a problem, usually the russifier uses the file "\BmGame\Config\Installer.ini" which says
```
[Language]
Language=rus
```
but I think "BmLauncher" uses its file "C:\Users \***\Documents\Square Enix\Batman Arkham Asylum GOTY\BmGame\Config\BmEngine.ini".
If you replace "int" with "rus" in line 22 (Language=), then the game starts with a new launcher and with the Russian language.
Thanks
![Screenshot_2](https://user-images.githubusercontent.com/69117971/163865505-a044a6c2-fbda-46d7-9f2e-60a9fb7c6d65.png)
![Screenshot_1](https://user-images.githubusercontent.com/69117971/163865544-90beb124-dad0-4136-aef9-ce21193dfc32.png)

(Maybe I made a mistake with the file that the standard launcher uses by default, maybe it looks at the file as well "C:\Users \***\Documents\....\BmGame\Config\UserEngine.ini")

**Comment by neatodev** [comment]
> (Maybe I made a mistake with the file that the standard launcher uses by default, maybe it looks at the file as well "C:\Users ***\Documents....\BmGame\Config\UserEngine.ini")

It does use BmEngine. 

I'll look into if I can do anything for unofficial languages, but I need a bigger sample size than one localization.

**Comment by w4rd3ll** [comment]
https://www.pcgamingwiki.com/wiki/Batman:_Arkham_Asylum

Here is a list of translations, and links to them

**Comment by neatodev** [comment]
I'm aware, I don't speak those languages though. I've already failed to install the russian localization due to the language and broken font barrier, so I would need a native speaker to walk through the process with me for each language.

**Comment by w4rd3ll** [comment]
The links where to find me are written in the profile.

--
upd:
1. I checked the Czech language. it replaces the original English language files. The "int" parameter is used. Ok.
2. Hungarian - 404 not found.
3. Japanese - also replaces English. Ok.
4. Brazilian Portuguese - also replaces, but I don't have fonts in the game.
5. Polish - also replaces English. Ok.
6. Turkish - 404 not found.
Only the Russian language does NOT use "int".
I think you can just add a line with the Russian language in the launcher.
The game was officially published in Russia on discs by the company "New Disc \ Новый Диск", so the localization was official.

**Comment by neatodev** [comment]
Thank you for looking into this for me. I'll come up with a decent way to implement it and update the launcher ASAP.

**Comment by neatodev** [comment]
Added support for unofficial language patches here: https://github.com/neatodev/BmLauncher/commit/f274f38efeaa27699cf7c2f86e2ae3fc93eb604b

Please download the newest release to try it out.

**Comment by w4rd3ll** [comment]
Sorry, but it didn't work. I have to manually replace "Language=rus" in "BmEngine.ini" in line 22, and only then localization works.
Now everything looks like the inscription "Unofficial" appeared instead of an empty line. This does not solve the problem.

[Video-file on Google Drive](https://drive.google.com/file/d/17dNL7R1YmefGI8W23SH-kTMVEdicnnK_)

**Comment by neatodev** [comment]
This is the intended behavior.

The thought process is this:

Download a language patch, install it, it either overwrites int, which is fine and explained in the tooltip for language or it automatically sets its own language parameter (i.e. ‘rus’). The launcher then detects the parameter as unofficial and does not overwrite it.

Edit:
The issue that you have in your video is that the BmEngine file is read only (because of previous launcher usage) and the installer can’t set the value to rus. In a normal use case you would install the patch first and then the launcher.
