### ISSUE TITLE
Error When Trying to put framerate above 62

### ISSUE THREAD

**Issue by Candyman760** [neatodev/BmLauncher#3]
This might not be an error with your program, but I could still really use some help if you know about this.  Every time I try to change the frame cap, I got this error.  I haven't modified any files aside from installing the launcher.  Some help would be really appreciated.

![Capture](https://user-images.githubusercontent.com/70260815/91280156-62dad880-e754-11ea-8011-779fa82dd351.PNG)

**Comment by neatodev** [comment]
This is caused either due to a bad NVIDIA driver install or outdated drivers.
The recommended course of action is as follows:
1. Download [Display Driver Uninstaller](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)
2. Choose "Clean & Restart" and let the application wipe your GPU drivers completely.
3. After the restart, download the newest NVIDIA drivers directly from [HERE](https://www.nvidia.com/Download/index.aspx) or use [GeForce Experience](https://www.nvidia.com/en-gb/geforce/geforce-experience/).

This should resolve all issues relating to the "NVAPI_ACCESS_DENIED" exception.
